### PR TITLE
DSND-3111: Process officer id on delete

### PR DESCRIPTION
**Pull request by sthompsonCH**
This PR implements new logic for deletion of appointments. We now take `officer_id` as a request param on the DELETE endpoint. 

In addition, if the appointment has already been deleted, we can send a valid resource change request still by using the officer_id, even when there is no resource in Mongo.

[DSND-3111](https://companieshouse.atlassian.net/browse/DSND-3111)

[DSND-3111]: https://companieshouse.atlassian.net/browse/DSND-3111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Review by cgregoryCH — APPROVED** [review]

**Pull request merged**
